### ISSUE TITLE
flux RSS

### ISSUE THREAD

**Issue by EKlevrai** [Difegue/eeisti-web#2]
parce que je sens que vous m'enverrez pas de mails pour la prochaine LAN !

**Comment by Difegue** [comment]
hé c'est presque une bonne idée

**Comment by EKlevrai** [comment]
ptet aussi une newsletter

**Comment by Difegue** [comment]
https://github.com/Difegue/eeisti-web/commit/4cebc410211967fd155953260417416779763953
hop
